### ISSUE TITLE
Revisar texto de apresentação

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/pyne2023#10]
Revisar texto de apresentação do evento, disponível na sessão "Conheça mais sobre a cidade-sede da PyNE 2023!"

-------
Texto atual:
Link (atualizar apenas parte em vermelho/rosa): https://docs.google.com/document/d/1WKd3h2iKzPaGX2-RhKqJIG0xGqGJg1f3fYkSof4bRz8/edit#heading=h.ho4kvb4wc03c

A PyNE este ano será sediada em Salvador - Bahia , capital e maior cidade da Bahia. A sua história está vinculada à chegada dos portugueses na costa brasileira, mais especificamente na região da Baía de Todos os Santos foi a primeira capital do Brasil

Considerada o centro da cultura afro-brasileira no Brasil. O território soteropolitano possui belas paisagens geográficas, e se beneficia de características muito específicas. Tem um clima quente e ensolarado o ano todo; a beleza natural de praias, como Ondina, Arembepe, Farol da Barra, Amaralina, e de lagoas, como a do Abaeté; as manifestações variadas da cultura negra, como a rica e saborosa culinária, música e ritmos revolucionários, sincretismo religioso, terreiros de candomblé e exibições de capoeira - tudo relacionado com o respeito, preservação e reverência à ancestralidade de seu povo!

Há ainda um belo conjunto arquitetônico remanescentes da época da colonização que representa um pedaço vivo da história do Brasil. A cidade registra manifestações culturais e religiosas importantes, sendo conhecida, por exemplo, pelos festejos de Senhor do Bonfim, Iemanjá, Carnaval e Ano-Novo.

Predominam em Salvador as atividades de serviços, turismo e comércio, mas é marcante o crescimento da industrialização e tecnologia nomeada como uma das cidades inteligentes do nordeste por atividades do dia a colocou no primeiro lugar do Nordeste no Ranking Connected Smart Cities, que aponta as cidades mais conectadas e inteligentes do país.

**Comment by cecivieira** [comment]
@jadefigueredo a sugestão de alteração recebida no grupo:

https://t.me/pyne2020/4719
De forma bem simples dá para tirar e trazer a referência que abre o segundo parágrafo para cima:

"A PyNE este ano será sediada em Salvador, capital da Bahia e considerada o centro da cultura afro-brasileira no Brasil."

Sem muitas mexidas, só trazer o que é importante para frente, tira a incorreção e segue o baile.

**Comment by jadefigueredo** [comment]
Link do texto alterado: https://docs.google.com/document/d/1yL8UTwD-sqZtvLZEOx_tbmCy30rUKu9YG4KjE6sxCf4/edit?usp=sharing
------------------------------------------------------------------------------------------
@cecivieira Seguem as alterações:

"A PyNE este ano será sediada na cidade de Salvador, primeira capital do Brasil e maior cidade da Bahia, considerada o centro da cultura afro-brasileira no Brasil. O território soteropolitano possui belas paisagens geográficas, e, se beneficia de características muito específicas como a presença do clima quente e ensolarado durante todo ano e a beleza natural de praias como: Ondina, Farol da Barra, Amaralina, e lagoas, como a do Abaeté.  Além disso, as manifestações variadas da fé e cultura do povo negro, expressadas através da culinária, nos ritmos, nos terreiros de candomblé ou comemorações do sincretismo religioso - Demonstrando o respeito, preservação e reverência à ancestralidade de seu povo!

Há ainda um belo conjunto arquitetônico que representa um pedaço vivo da história do Brasil. A cidade registra manifestações culturais e religiosas importantes, sendo conhecida, por exemplo, pelos festejos de Senhor do Bonfim, Iemanjá, Carnaval e Ano-Novo. Predominam em Salvador as atividades de serviços, como o turismo e o comércio. Tem sido marcante o crescimento da industrialização e tecnologia, o que fez com que a cidade fosse nomeada como uma das cidades inteligentes do nordeste,  alcançando o primeiro lugar no Ranking Connected Smart Cities, que aponta as cidades mais conectadas e inteligentes do país".

**Comment by tiidadavena** [comment]
Foi aberta uma issue no site para implementar a correção do texto.
