### ISSUE TITLE
Alterar texto do site - Descrição da cidade

### ISSUE THREAD

**Issue by tiidadavena** [pythonNordeste/pyne2023#11]
Alterar o texto de apresentação da cidade seguindo o texto desta issue:
https://github.com/pythonNordeste/pyne2023/issues/10

**Comment by PatriciaSilvaRecife** [comment]
Conheça mais sobre a cidade sede da PyNE 2023!

A PyNE este ano será sediada na cidade de Salvador, primeira capital do Brasil e maior cidade da Bahia, considerada o centro da cultura afro-brasileira no Brasil. A sua história está vinculada à chegada dos portugueses na costa brasileira, mais especificamente na região da Baía de Todos os Santos.

Considerada o centro da cultura afro-brasileira no Brasil. O território soteropolitano possui belas paisagens geográficas, e se beneficia de características muito específicas. Tem um clima quente e ensolarado o ano todo; a beleza natural de praias, como Ondina, Arembepe, Farol da Barra, Amaralina, e de lagoas, como a do Abaeté; as manifestações variadas da cultura negra, como a rica e saborosa culinária, música e ritmos revolucionários, sincretismo religioso, terreiros de candomblé e exibições de capoeira - tudo relacionado com o respeito, preservação e reverência à ancestralidade de seu povo!
Há ainda um belo conjunto arquitetônico remanescentes da época da colonização que representa um pedaço vivo da história do Brasil. A cidade registra manifestações culturais e religiosas importantes, sendo conhecida, pelos festejos do Senhor do Bonfim, Iemanjá, Carnaval e Ano Novo.

Predominam em Salvador as atividades de serviços, turismo e comércio, mas é marcante o crescimento da industrialização e tecnologia nomeada como uma das cidades inteligentes do Nordeste. Ficou em primeiro lugar do Nordeste no Ranking Connected Smart Cities, que aponta as cidades mais conectadas e inteligentes do País.

**Comment by tiidadavena** [comment]
@PatriciaSilvaRecife dá uma olhadinha neste link com a descrição atualizada: 

https://deploy-preview-15--pythonnordeste2023.netlify.app/

**Comment by PatriciaSilvaRecife** [comment]
Ficou muito bom @tiidadavena 
Agora ficará em dois espaços? Pois o texto se encontra na home e na descrição sobre a cidade.

**Comment by tiidadavena** [comment]
> Ficou muito bom @tiidadavena Agora ficará em dois espaços? Pois o texto se encontra na home e na descrição sobre a cidade.


Isso! Tomei a liberdade de quebrar o texto em diferentes linhas para melhorar a leitura.
