### ISSUE TITLE
Adicionar link do Pretalx no site

### ISSUE THREAD

**Issue by tiidadavena** [pythonNordeste/pyne2023#26]
Link da grade: https://pretalx.com/python-nordeste-2023/schedule/

**Comment by anjinha-oliveira** [comment]
@tiidadavena , não entendi o que você falou ai em cima amiga. Pode me explicar? Posso começar a fazer hoje a tarde essa issue

**Comment by anjinha-oliveira** [comment]
"Acho que poderias duplicar a parte da seção de atividades e colocar um h3" 
Eu não encontrei essa seção. Vou precisar de um print de onde deve ser adicionado o link pra que eu não coloque em lugar errado kk 

Seria nessa página de "Chamada de atividade" ou na "Página inicial"?

![pretalx com_python-nordeste-2023_cfp (2)](https://github.com/pythonNordeste/pyne2023/assets/89156781/4fc3eaf4-b835-40a4-bdb7-e1e2ed393b82)

@g-101 , @Carine-Neris

**Comment by tiidadavena** [comment]
> "Acho que poderias duplicar a parte da seção de atividades e colocar um h3" Eu não encontrei essa seção. Vou precisar de um print de onde deve ser adicionado o link pra que eu não coloque em lugar errado kk
> 
> Seria nessa página de "Chamada de atividade" ou na "Página inicial"?
> 
> ![pretalx com_python-nordeste-2023_cfp (2)](https://user-images.githubusercontent.com/89156781/244752714-4fc3eaf4-b835-40a4-bdb7-e1e2ed393b82.png)
> 
> @g-101 , @Carine-Neris

Opa, acabei deixando a descrição mt genérica 
É pra adicionar um link do site da PyNE com um botão redirecionando para este link: https://pretalx.com/python-nordeste-2023/schedule/


Pode ser o mesmo estilo do btn de  Submissão de atividades" 

![image](https://github.com/pythonNordeste/pyne2023/assets/12106738/45860a96-3a5c-4868-9728-cb0d5d223292)

**Comment by Carine-Neris** [comment]
@anjinha-oliveira  no caso seria um botão com esse link:https://pretalx.com/python-nordeste-2023/schedule/.
Acho que poderia ser criada uma sessão abaixo do botão  de submissão  de atividade com o botão da grade ou deixar isso no nav bar?

**Comment by anjinha-oliveira** [comment]
@Carine-Neris , acho que o problema de deixar na mesma nav é que depois, acredito que vão querer mudar um dos botões pra não ficar iguais. Isso não atrapalharia no futuro?
Não é melhor criar um nav especifico pra esse botão que vai ser adicionado?

**Comment by anjinha-oliveira** [comment]
@Carine-Neris , entendi agora sua pergunta. Eu poderia testar aqui como fica melhor. Mas assim... o nav ta quebrado, a gente teria que organizar a nav primeiro antes de colocar esse link lá. Vou adicionar um botão em baixo do de submissão e mando pra vcs avaliarem como ficou. Pode ser?

**Comment by anjinha-oliveira** [comment]
Acho que dá pra gente colocar um ao lado do outro. Porque dessa forma, fica esquisito ou podemos colocar no nav também, só que teremos que arrumar ele pois está quebrando. 

Ficou dessa forma: 

![_C__Users_Angela_Projetos_pyne2023_index html (7)](https://github.com/pythonNordeste/pyne2023/assets/89156781/42500947-7ed1-43ce-829a-114f9a9c6bb8)

**Comment by tiidadavena** [comment]
> Acho que dá pra gente colocar um ao lado do outro. Porque dessa forma, fica esquisito ou podemos colocar no nav também, só que teremos que arrumar ele pois está quebrando.
> 
> Ficou dessa forma:
> 
> ![_C__Users_Angela_Projetos_pyne2023_index html (7)](https://user-images.githubusercontent.com/89156781/244795068-42500947-7ed1-43ce-829a-114f9a9c6bb8.png)

Ficou massa! Acho que podemos criar uma seção com cor branca + h3 com o título "Submissão de atividades" com botão na cor desse verde-piscina da seção "Sobre a cidade"

**Comment by anjinha-oliveira** [comment]
Gente, tenho uma duvida... Tem necessidade de colocar esse botão agora? A gente já tem a grade de palestras definidas? Porque pra mim faz mais sentido a gente organizar o nav bar primeiro e colocar esse botão na nav como @Carine-Neris falou

**Comment by tiidadavena** [comment]
> Gente, tenho uma duvida... Tem necessidade de colocar esse botão agora? A gente já tem a grade de palestras definidas? Porque pra mim faz mais sentido a gente organizar o nav bar primeiro e colocar esse botão na nav como @Carine-Neris falou

Sim sim, porque é um dos requisitos para a gente solicitar apoio financeiro da PSF (Python Software Foundation).

**Comment by tiidadavena** [comment]
Acho que a gnt pode só adicionar o botão já que o botão de submissão a gente vai remover na semana que vem

**Comment by anjinha-oliveira** [comment]
aaah, entendi. Nesse cas

> > Acho que dá pra gente colocar um ao lado do outro. Porque dessa forma, fica esquisito ou podemos colocar no nav também, só que teremos que arrumar ele pois está quebrando.
> > Ficou dessa forma:
> > ![_C__Users_Angela_Projetos_pyne2023_index html (7)](https://user-images.githubusercontent.com/89156781/244795068-42500947-7ed1-43ce-829a-114f9a9c6bb8.png)
> 
> Ficou massa! Acho que podemos criar uma seção com cor branca + h3 com o título "Submissão de atividades" com botão na cor desse verde-piscina da seção "Sobre a cidade"

Nesse caso a gente faz outra issue para estilização dos botões?

**Comment by tiidadavena** [comment]
> > > Acho que dá pra gente colocar um ao lado do outro. Porque dessa forma, fica esquisito ou podemos colocar no nav também, só que teremos que arrumar ele pois está quebrando.
> > > Ficou dessa forma:
> > > ![_C__Users_Angela_Projetos_pyne2023_index html (7)](https://user-images.githubusercontent.com/89156781/244795068-42500947-7ed1-43ce-829a-114f9a9c6bb8.png)
> > 
> > 
> > Ficou massa! Acho que podemos criar uma seção com cor branca + h3 com o título "Submissão de atividades" com botão na cor desse verde-piscina da seção "Sobre a cidade"
> 
> Aah, sim. Entendi.
> 
> Nesse caso a gente faz outra issue para estilização dos botões?

Precisa não; sobre a cor sugeri a cor turquesa da seção da cidade mas fique à vontade pra testar outras cores

**Comment by anjinha-oliveira** [comment]
@tiidadavena Tava tentando imaginar como seria a seção que vc tinha falado. É dessa forma? Se não for, me fala que ajusto

![github](https://github.com/pythonNordeste/pyne2023/assets/89156781/a3543912-2dbc-4eda-9bee-c6623e7884e3)
