### ISSUE TITLE
Inserir plano de patrocínio

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/pyne2023#3]
*Descrição*

Adicionar um botão que redireciona para o Drive do Plano de Patrocínio

**Comment by tiidadavena** [comment]
- Seção com CTA para redirecionar ao link do Drive

**Comment by lipemorais** [comment]
Versão final do plano de patrocínio.
https://drive.google.com/drive/folders/1oi7UYRP-RPibLOdAiXeIskwsIREzQorM

**Comment by tiidadavena** [comment]
#6
