### ISSUE TITLE
Inserir logo da Globo (patrocinadora bronze)

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/pyne2023#33]
![image](https://github.com/pythonNordeste/pyne2023/assets/30605862/3785b02b-2641-4dc3-b383-e8ad7ea2f40f)

**Comment by g-101** [comment]
em qual seção ficara essa logo?

**Comment by tiidadavena** [comment]
> em qual seção ficara essa logo?

Precisaria criar uma nova seção - uma sugestão seria acima das redes sociais

**Comment by tiidadavena** [comment]
Logo adicionada: https://2023.pythonnordeste.org/
