### ISSUE TITLE
Inserir apoiadoras

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/pyne2023#34]
Inserir área de apoiadores com as logos da Politécnica da UFBA e demais projetos:

https://www.eng.ufba.br/
![image](https://github.com/pythonNordeste/pyne2023/assets/30605862/92d37165-5e6a-429b-82db-987d1ac17ca4)

https://gamma-ufba.github.io/index.html
![image](https://github.com/pythonNordeste/pyne2023/assets/30605862/e42948f5-f267-4bab-b372-83ac1ebf1431)

https://www.instagram.com/cienciadedadosnaep/
![image](https://github.com/pythonNordeste/pyne2023/assets/30605862/4e1ffbc2-a405-484e-b665-e109760858c4)

**Comment by anjinha-oliveira** [comment]
Vou fazer essa issue. Preciso saber qual a categoria de patrocínio, bronze ou ouro? 
Se for ouro, fica no tamanho maior a imagem?

**Comment by cecivieira** [comment]
@anjinha-oliveira essa é a categoria de Apoio
As logos costumam ser do tamanho proporcional a categoria de apoio, mas eu não saberia dizer qual é. Talvez @tiidadavena consiga ajudar a definir isso

**Comment by anjinha-oliveira** [comment]
Ahh, ok! Vou verificar no código o tamanho.

**Comment by tiidadavena** [comment]
> Ahh, ok! Vou verificar no código o tamanho.

No da Globo a gnt limitou o tamanho de largura e altura para 100px
