### ISSUE TITLE
Trocar cor da seção "Patrocinadoras"

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/pyne2023#35]
Talvez seja interessante trocar a cor da seção "Patrocinadoras" para que seja mais fácil a leitura e entendimento da troca de seção.
Minha sugestão é colocar o background em azul, igual a da seção "Conheça mais sobre a cidade-sede da PyNE 2023!". Dessa forma, haverá uma alternancia de cor em cada seção

**Comment by tiidadavena** [comment]
> Talvez seja interessante trocar a cor da seção "Patrocinadoras" para que seja mais fácil a leitura e entendimento da troca de seção. Minha sugestão é colocar o background em azul, igual a da seção "Conheça mais sobre a cidade-sede da PyNE 2023!". Dessa forma, haverá uma alternancia de cor em cada seção

Concordo com a ideia: solicitei a lista completa de cores para Carol para realizar alguns ajustes de cores na seção.

**Comment by anjinha-oliveira** [comment]
Oi, gente. Vou mudar a cor do background para coral no meu PR: https://github.com/pythonNordeste/pyne2023/pull/36
já com adição das logos. Pode ser?
