### ISSUE TITLE
Inserir Botcity como patrocinadora ouro

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/pyne2023#37]

**Comment by cecivieira** [comment]
Verificar link para logo nessa planilha:
https://docs.google.com/spreadsheets/d/1EfPf_xKD8nDpxNVhVhTOPq5MBEhv9fUD71tExAN16t4/edit#gid=1103660704

**Comment by tiidadavena** [comment]
A empresa ainda não anexou a logo

**Comment by tiidadavena** [comment]
Ainda aguardando o envio da logo por parte da empresa

**Comment by tiidadavena** [comment]
Logo adicionada na última versão do site: https://2023.pythonnordeste.org/

![image](https://github.com/pythonNordeste/pyne2023/assets/12106738/132ad109-c1d8-42d7-932c-b700d3a2cfeb)

**Comment by cecivieira** [comment]
@tiidadavena não consigo visualizar a logo da Botcity no site

**Comment by tiidadavena** [comment]
> @tiidadavena não consigo visualizar a logo da Botcity no site

Perdão, respondi na issue errada

**Comment by tiidadavena** [comment]
A empresa já incluiu a logo e a incluiremos no site ASAP

**Comment by tiidadavena** [comment]
Logo da patrocinadora Botcity adicionado ao site:
![image](https://github.com/pythonNordeste/pyne2023/assets/12106738/d27d8ff5-6a96-4cfa-a1c6-5b0f4216ad34)


Já disponível no site [atual](https://2023.pythonnordeste.org/)
