### ISSUE TITLE
Inserir Elastic como patrocinadora ouro

### ISSUE THREAD

**Issue by cecivieira** [pythonNordeste/pyne2023#38]

**Comment by cecivieira** [comment]
Verificar link para logo nessa planilha:
https://docs.google.com/spreadsheets/d/1EfPf_xKD8nDpxNVhVhTOPq5MBEhv9fUD71tExAN16t4/edit#gid=1103660704

**Comment by cecivieira** [comment]
@tiidadavena a empresa preencheu o formulário

**Comment by tiidadavena** [comment]
Perfeito! Vamos add no site!

**Comment by cecivieira** [comment]
Logo adicionada
