### ISSUE TITLE
Transferência de domínio DNS

### ISSUE THREAD

**Issue by tiidadavena** [pythonNordeste/pyne2023#43]
Durante o deploy do redesign do site, o Netlify serviu o site com erros de layout não encontrados no review app.

Foi feita a transferência para um novo sistema de deploy, cujo CNAME é: https://pyne2023.onrender.com/

cc @fabiocerqueira

**Comment by fabiocerqueira** [comment]
CNAME foi atualizado

**Comment by tiidadavena** [comment]
Muito obrigada pela ajuda, @fabiocerqueira !!!
